version: '2.4'

services:
  hms:
    build:
      context: ../base
    networks:
      - frontend

  proxy:
    build:
      context: .
    ports:
      - 80:80
    networks:
      - frontend
      - backend

  hms_api:
    build:
      context: ../api
      args:
        - APP_PORT=3031
        - APP_NAME=HMS
    networks:
      - backend

  activity_api:
    build:
      context: ../api
      args:
        - APP_PORT=3032
        - APP_NAME=ACTIVITY
    networks:
      - backend

  parlor_api:
    build:
      context: ../api
      args:
        - APP_PORT=3033
        - APP_NAME=PARLOR
    networks:
      - backend

networks:
  frontend:
  backend: